#!/usr/bin/env bash
# scripts/install-linux.sh — install the watcher as a systemd user unit.
#
# duckbot-secret-scan: allowlist-file
#
# Cross-platform companion to scripts/install-macos.sh (launchd).
#
# What it does:
#   1. Writes a systemd user unit file to ~/.config/systemd/user/
#   2. Enables linger so the unit runs even when the user is logged out
#   3. Starts + enables the unit
#
# Requirements:
#   - Linux (any distro with systemd)
#   - loginctl enable-linger $USER (one-time; requires sudo)
#   - The venv at $REPO_ROOT/.venv (run scripts/install.sh first)
#
# Usage (from repo root):
#   ./scripts/install-linux.sh
#
# Manage with:
#   systemctl --user status duckbot-memory-watcher
#   systemctl --user restart duckbot-memory-watcher
#   systemctl --user stop duckbot-memory-watcher
#   journalctl --user -u duckbot-memory-watcher -f

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Make shell + helper scripts executable. The `*.sh` glob misses
# `duckbot-ask` (no extension) and the Python helpers, so chmod them
# explicitly. Silently ignore if not present.
chmod +x scripts/*.sh scripts/duckbot-ask 2>/dev/null || true
chmod +x scripts/_format_*.py 2>/dev/null || true

if [[ "$(uname -s 2>/dev/null || echo unknown)" != "Linux" ]]; then
  echo "❌ install-linux.sh: this is for Linux only. Detected: $(uname -s)" >&2
  exit 1
fi

# 1. Validate venv
if [[ ! -x .venv/bin/python ]]; then
  echo "❌ .venv/bin/python not found. Run scripts/install.sh first." >&2
  exit 1
fi

# 2. Write the user unit
UNIT_DIR="$HOME/.config/systemd/user"
mkdir -p "$UNIT_DIR"
UNIT_PATH="$UNIT_DIR/duckbot-memory-watcher.service"

cat > "$UNIT_PATH" <<EOF
# duckbot-secret-scan: allowlist-file
# Auto-generated by scripts/install-linux.sh
[Unit]
Description=DuckBot memory watcher (auto-updates the brain from filesystem changes)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$REPO_ROOT
ExecStart=$REPO_ROOT/.venv/bin/python -m src.watcher run $REPO_ROOT/memory $REPO_ROOT/AGENTS.md $REPO_ROOT/SOUL.md $REPO_ROOT/USER.md $REPO_ROOT/IDENTITY.md $REPO_ROOT/TOOLS.md
Restart=on-failure
RestartSec=10
StandardOutput=append:$REPO_ROOT/data/watcher.log
StandardError=append:$REPO_ROOT/data/watcher.err.log

[Install]
WantedBy=default.target
EOF

echo "✓ Wrote $UNIT_PATH"

# 3. Reload + enable + start
systemctl --user daemon-reload
systemctl --user enable duckbot-memory-watcher.service
systemctl --user restart duckbot-memory-watcher.service

# 4. Linger (so the unit survives logout)
if command -v loginctl >/dev/null 2>&1; then
  if ! loginctl show-user "$USER" 2>/dev/null | grep -q 'Linger=yes'; then
    echo ""
    echo "⚠ To keep the watcher running after logout, enable linger:"
    echo "    sudo loginctl enable-linger $USER"
    echo "  (one-time setup; requires sudo)"
  fi
fi

echo ""
echo "=== Watcher installed and started ==="
echo ""
echo "Manage with:"
echo "  systemctl --user status duckbot-memory-watcher"
echo "  systemctl --user restart duckbot-memory-watcher"
echo "  systemctl --user stop duckbot-memory-watcher"
echo "  journalctl --user -u duckbot-memory-watcher -f"
echo "  tail -f $REPO_ROOT/data/watcher.log"
