"""
skillgen.py — auto-generate agentskills.io-compatible skill manifests.

When `brain_remember` is called with `kind=skill_candidate`, we generate a SKILL.md
file in `skills/<slug>/SKILL.md` that follows the agentskills.io open
standard. The format (matching our existing skills):

    ---
    name: <slug>
    description: <one-line>
    metadata:
      {"openclaw": {"emoji": "<emoji>", "requires": {"bins": ["python"]}}}
    ---

    # <Title>

    <markdown body — instructions, examples, etc.>

    Powered by duckbot-rag-memory.

Why auto-create: when an agent solves a new task successfully, the
memory should persist as a reusable skill. The agent shouldn't have
to write the SKILL.md by hand — the brain distills the task + outcome
into a manifest automatically.

Cost: zero (pure templating, no LLM call by default). An optional
`--llm` flag could route through LM Studio for higher-quality
generation, but the deterministic path is enough for v0.1.
"""
from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Optional


def _slugify(name: str) -> str:
    """Convert a skill name to a filesystem-safe slug.

    Examples:
        "How to restart the BATMAN container"
            -> "how-to-restart-the-batman-container"
        "Deploy / Setup / Config"
            -> "deploy-setup-config"
    """
    s = (name or "").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = s.strip("-")
    return s or "untitled-skill"


def _guess_emoji(text: str) -> str:
    """Pick a sensible default emoji from keywords in the text.

    Falls back to a generic sparkle. Better than nothing for v0.1; an
    LLM-driven path could pick better.
    """
    t = (text or "").lower()
    for kw, emoji in [
        ("docker", "🐳"), ("container", "🐳"),
        ("git", "🔀"), ("commit", "🔀"),
        ("test", "🧪"), ("pytest", "🧪"),
        ("deploy", "🚀"), ("release", "🚀"),
        ("fix", "🔧"), ("bug", "🔧"),
        ("memory", "🧠"), ("brain", "🧠"), ("recall", "🧠"),
        ("data", "📊"), ("chart", "📊"),
        ("chat", "💬"), ("message", "💬"),
        ("email", "📧"),
        ("calendar", "📅"), ("schedule", "📅"),
        ("file", "📄"), ("document", "📄"),
        ("search", "🔍"), ("find", "🔍"),
        ("audio", "🎵"), ("music", "🎵"),
    ]:
        if kw in t:
            return emoji
    return "✨"


def render_skill_md(
    name: str,
    description: str,
    body_markdown: str,
    emoji: Optional[str] = None,
    requires_bins: Optional[list[str]] = None,
) -> str:
    """Render a SKILL.md string from the inputs.

    Args:
        name: human-readable skill name ("Restart the BATMAN container")
        description: one-line, plain-text, used as the frontmatter
            description. Should be a clear trigger phrase like
            "Use this when X happens so you can Y."
        body_markdown: the markdown body (instructions, examples, etc.)
        emoji: optional override; defaults to a keyword guess.
        requires_bins: list of binary dependencies (e.g. ["python", "git"]).
            Defaults to ["python"].

    Returns:
        A complete SKILL.md string ready to write to disk.
    """
    slug = _slugify(name)
    if emoji is None:
        emoji = _guess_emoji(f"{name} {description} {body_markdown}")
    bins = requires_bins or ["python"]
    # Quote the metadata as a single-line JSON (the standard).
    import json
    metadata = {"openclaw": {"emoji": emoji, "requires": {"bins": bins}}}

    frontmatter_lines = [
        "---",
        f"name: {slug}",
        f"description: {description.strip()}",
        "metadata:",
        f"  {json.dumps(metadata)}",
        "---",
        "",
    ]
    frontmatter = "\n".join(frontmatter_lines)

    # If the body doesn't already start with a title, add one.
    body = body_markdown.strip()
    if not body.startswith(f"# "):
        title = name.strip()
        body = f"# {title}\n\n{body}"

    # Footer with provenance.
    today = date.today().isoformat()
    footer = (
        f"\n\n---\n\n"
        f"_Auto-generated by duckbot-rag-memory on {today}._\n"
        f"_Source: brain_remember(kind=skill_candidate). Edit freely._\n"
    )

    return frontmatter + body + footer


def write_skill(
    skills_dir: Path,
    name: str,
    description: str,
    body_markdown: str,
    emoji: Optional[str] = None,
    requires_bins: Optional[list[str]] = None,
    overwrite: bool = False,
) -> Path:
    """Render + write a SKILL.md. Returns the path written.

    Default behavior: if the file already exists, refuse to overwrite
    (pass overwrite=True to force). Names with the same slug share the
    same path — callers should pre-check the slug if they want to
    version the same skill.

    Args:
        skills_dir: root of the skills directory (e.g. ~/.../skills/).
        name: human-readable skill name.
        description: one-line.
        body_markdown: markdown body.
        emoji: optional override.
        requires_bins: list of binary deps.
        overwrite: if False and the file exists, raise FileExistsError.
    """
    slug = _slugify(name)
    out_path = Path(skills_dir) / slug / "SKILL.md"
    if out_path.exists() and not overwrite:
        raise FileExistsError(
            f"skill already exists at {out_path}. Pass overwrite=True to replace."
        )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(
        render_skill_md(name, description, body_markdown, emoji, requires_bins),
        encoding="utf-8",
    )
    return out_path


def render_from_memory(
    name: str,
    description: str,
    instructions: list[str],
    example: str = "",
    emoji: Optional[str] = None,
) -> str:
    """Convenience: render from a structured dict (typical shape after
    a successful task).

    Args:
        name: skill name
        description: one-line description
        instructions: list of step-by-step instructions
        example: optional worked example
        emoji: optional override
    """
    lines = [
        f"## When to Use",
        "",
        f"Use this skill when: {description.strip()}",
        "",
        f"## Instructions",
        "",
    ]
    for i, step in enumerate(instructions, 1):
        lines.append(f"{i}. {step}")
    lines.append("")
    if example:
        lines.extend(["## Example", "", example.strip(), ""])
    return "\n".join(lines)
